import type { OnboardingApplication } from '@/lib/onboarding-types'

export const MOCK_APPLICATIONS: OnboardingApplication[] = [
  {
    id: 'mock-1', intake_token: 'tok1', business_name: 'Coastal Café LLC', owner_name: 'Maria Santos',
    owner_email: 'maria@coastalcafe.com', owner_phone: null, business_type: 'LLC', ein: null,
    website: null, mcc: '5812', monthly_volume: '45000', avg_ticket: '32', card_present_percent: '80',
    years_in_business: '3', business_address: null, city: 'Miami', state: 'FL', zip: null,
    owner_address: null, owner_city: null, owner_state: null, owner_zip: null,
    owner_dob: null, owner_ssn_last4: null, ownership_percent: '100', current_processor: null,
    chargeback_history: 'none', co_owners: [], risk_tier: 'low', current_phase: 'document_review',
    link_status: 'submitted', ai_summary: null, ai_risk_reasoning: null,
    ai_preapproval_recommendation: null, ai_risk_score: 22, website_compliance: null,
    match_list_checked: true, portal_email: null, client_auth_user_id: null, duplicate_of: null,
    intake_token_expires_at: '2026-07-01T00:00:00Z', created_at: '2026-05-10T12:00:00Z',
    intake_submitted_at: '2026-05-12T09:00:00Z', preapproved_at: null, live_at: null, created_by: null,
  },
  {
    id: 'mock-2', intake_token: 'tok2', business_name: 'TechPay Solutions', owner_name: 'James Okafor',
    owner_email: 'james@techpay.io', owner_phone: '3055550101', business_type: 'Corp', ein: null,
    website: 'https://techpay.io', mcc: '7372', monthly_volume: '120000', avg_ticket: '850',
    card_present_percent: '5', years_in_business: '2', business_address: null, city: 'Austin',
    state: 'TX', zip: null, owner_address: null, owner_city: null, owner_state: null, owner_zip: null,
    owner_dob: null, owner_ssn_last4: null, ownership_percent: '60', current_processor: null,
    chargeback_history: '1.2%', co_owners: [], risk_tier: 'high', current_phase: 'pursuit',
    link_status: 'submitted', ai_summary: null, ai_risk_reasoning: null,
    ai_preapproval_recommendation: null, ai_risk_score: 68, website_compliance: null,
    match_list_checked: false, portal_email: null, client_auth_user_id: null, duplicate_of: null,
    intake_token_expires_at: '2026-07-01T00:00:00Z', created_at: '2026-05-15T08:00:00Z',
    intake_submitted_at: '2026-05-17T10:00:00Z', preapproved_at: null, live_at: null, created_by: null,
  },
  {
    id: 'mock-3', intake_token: 'tok3', business_name: 'Green Sprout Market', owner_name: 'Priya Nair',
    owner_email: 'priya@greensprout.com', owner_phone: null, business_type: 'Sole_Proprietor', ein: null,
    website: null, mcc: '5411', monthly_volume: '28000', avg_ticket: '55', card_present_percent: '95',
    years_in_business: '7', business_address: null, city: 'Portland', state: 'OR', zip: null,
    owner_address: null, owner_city: null, owner_state: null, owner_zip: null,
    owner_dob: null, owner_ssn_last4: null, ownership_percent: '100', current_processor: null,
    chargeback_history: 'none', co_owners: [], risk_tier: 'low', current_phase: 'live',
    link_status: 'submitted', ai_summary: null, ai_risk_reasoning: null,
    ai_preapproval_recommendation: null, ai_risk_score: 12, website_compliance: null,
    match_list_checked: true, portal_email: null, client_auth_user_id: null, duplicate_of: null,
    intake_token_expires_at: '2026-07-01T00:00:00Z', created_at: '2026-05-01T10:00:00Z',
    intake_submitted_at: '2026-05-03T14:00:00Z', preapproved_at: '2026-05-20T00:00:00Z',
    live_at: '2026-06-01T00:00:00Z', created_by: null,
  },
  {
    id: 'mock-4', intake_token: 'tok4', business_name: 'Blaze E-Commerce', owner_name: 'Derek Wu',
    owner_email: 'derek@blazeco.com', owner_phone: '2125550199', business_type: 'LLC', ein: null,
    website: 'https://blazeco.com', mcc: '5999', monthly_volume: '75000', avg_ticket: '120',
    card_present_percent: '0', years_in_business: '1', business_address: null, city: 'New York',
    state: 'NY', zip: null, owner_address: null, owner_city: null, owner_state: null, owner_zip: null,
    owner_dob: null, owner_ssn_last4: null, ownership_percent: '100', current_processor: null,
    chargeback_history: '2.1%', co_owners: [], risk_tier: 'very_high', current_phase: 'document_review',
    link_status: 'submitted', ai_summary: null, ai_risk_reasoning: null,
    ai_preapproval_recommendation: null, ai_risk_score: 88, website_compliance: null,
    match_list_checked: false, portal_email: null, client_auth_user_id: null, duplicate_of: 'mock-2',
    intake_token_expires_at: '2026-07-01T00:00:00Z', created_at: '2026-05-20T09:00:00Z',
    intake_submitted_at: '2026-05-21T11:00:00Z', preapproved_at: null, live_at: null, created_by: null,
  },
  {
    id: 'mock-5', intake_token: 'tok5', business_name: 'Sunrise Spa', owner_name: 'Elena Vega',
    owner_email: 'elena@sunrisespa.com', owner_phone: '7025550144', business_type: 'LLC', ein: null,
    website: null, mcc: '7299', monthly_volume: '18000', avg_ticket: '90', card_present_percent: '100',
    years_in_business: '4', business_address: null, city: 'Las Vegas', state: 'NV', zip: null,
    owner_address: null, owner_city: null, owner_state: null, owner_zip: null,
    owner_dob: null, owner_ssn_last4: null, ownership_percent: '100', current_processor: null,
    chargeback_history: 'none', co_owners: [], risk_tier: 'medium', current_phase: 'partner_selection',
    link_status: 'submitted', ai_summary: null, ai_risk_reasoning: null,
    ai_preapproval_recommendation: null, ai_risk_score: 41, website_compliance: null,
    match_list_checked: true, portal_email: null, client_auth_user_id: null, duplicate_of: null,
    intake_token_expires_at: '2026-07-01T00:00:00Z', created_at: '2026-05-28T07:00:00Z',
    intake_submitted_at: '2026-05-29T16:00:00Z', preapproved_at: null, live_at: null, created_by: null,
  },
  {
    id: 'mock-6', intake_token: 'tok6', business_name: 'FastFuel Dispatch', owner_name: null,
    owner_email: 'ops@fastfuel.biz', owner_phone: null, business_type: null, ein: null,
    website: null, mcc: null, monthly_volume: null, avg_ticket: null, card_present_percent: null,
    years_in_business: null, business_address: null, city: null, state: null, zip: null,
    owner_address: null, owner_city: null, owner_state: null, owner_zip: null,
    owner_dob: null, owner_ssn_last4: null, ownership_percent: null, current_processor: null,
    chargeback_history: 'none', co_owners: [], risk_tier: 'unscored', current_phase: 'intake_sent',
    link_status: 'sent', ai_summary: null, ai_risk_reasoning: null,
    ai_preapproval_recommendation: null, ai_risk_score: null, website_compliance: null,
    match_list_checked: false, portal_email: null, client_auth_user_id: null, duplicate_of: null,
    intake_token_expires_at: '2026-07-01T00:00:00Z', created_at: '2026-06-03T14:00:00Z',
    intake_submitted_at: null, preapproved_at: null, live_at: null, created_by: null,
  },
]
